// Base de datos local
const DB = {
  load() {
    const data = JSON.parse(localStorage.getItem("gymdb_v1") || "{}");
    this.users = data.users || seedUsers();
    this.memberships = data.memberships || seedMemberships();
    this.attendance = data.attendance || []; // {id, clientId, type:'entrada'|'salida', at}
    this.payments = data.payments || []; // {id, clientId, amount, bank, note, at, user}
    this.entrenamientos = data.entrenamientos || []; // {id, clienteId, cedula, genero, secciones, fechaAsignacion, sucursal}
    this.plantillasWhatsApp = data.plantillasWhatsApp || seedPlantillasWhatsApp(); // {id, titulo, mensaje, categoria, activa, fechaCreacion}
    this.descuentos = data.descuentos || seedDescuentos(); // {id, nombre, monto, activo, fechaCreacion}
    this.pagosInformados = data.pagosInformados || []; // {id, fecha, banco, monto, detalle, detalleAdicional, creadoPor, fechaCreacion, estado}
    this.settings = data.settings || {
      sucursal: "Matriz",
      theme: "dark",
    };
    save();
  },
  users: [],
  memberships: [],
  attendance: [],
  payments: [],
  entrenamientos: [],
  plantillasWhatsApp: [],
  descuentos: [],
  pagosInformados: [],
  settings: {},
};

const save = () =>
  localStorage.setItem(
    "gymdb_v1",
    JSON.stringify({
      users: DB.users,
      memberships: DB.memberships,
      attendance: DB.attendance,
      payments: DB.payments,
      settings: DB.settings,
      entrenamientos: DB.entrenamientos || [],
      plantillasWhatsApp: DB.plantillasWhatsApp || [],
      descuentos: DB.descuentos || [],
      pagosInformados: DB.pagosInformados || [],
    })
  );

function seedMemberships() {
  return [
    {
      id: "m1",
      nombre: "Mensual",
      frecuencia: "30 días",
      monto: 25,
      sucursal: "Matriz",
      detalle: "Acceso ilimitado 30 días",
    },
    {
      id: "m2",
      nombre: "Trimestral",
      frecuencia: "90 días",
      monto: 65,
      sucursal: "Matriz",
      detalle: "Ahorra 13%",
    },
    {
      id: "m3",
      nombre: "Anual",
      frecuencia: "365 días",
      monto: 220,
      sucursal: "Norte",
      detalle: "Mejor precio",
    },
  ];
}

function seedUsers() {
  const now = NOW();
  const d = (n) => new Date(now.getTime() - n * 86400000);
  return [
    {
      id: "u1",
      nombres: "María",
      apellidos: "López",
      cedula: "1102345678",
      nacimiento: "1995-08-22",
      email: "maria@mail.com",
      telefono: "+593991112223",
      direccion: "Av. Amazonas",
      genero: "Mujer",
      foto: "",
      obraSocial: "IESS",
      notas: "Prefiere mañanas",
      tipo: "Cliente",
      activo: true,
      membresia: "m1",
      inscritoPrimera: d(190),
      membresiaInicio: d(20),
      membresiaFin: d(-10),
      saldo: 0,
      ultimoIngreso: d(1),
      creadoAt: d(2),
    },
    {
      id: "u2",
      nombres: "Juan",
      apellidos: "Pérez",
      cedula: "1712345678",
      nacimiento: "1990-11-10",
      email: "juan@mail.com",
      telefono: "+593997778889",
      direccion: "La Floresta",
      genero: "Hombre",
      foto: "",
      obraSocial: "",
      notas: "",
      tipo: "Cliente",
      activo: true,
      membresia: "m2",
      inscritoPrimera: d(400),
      membresiaInicio: d(50),
      membresiaFin: d(-40),
      saldo: 10,
      ultimoIngreso: d(45),
      creadoAt: d(10),
    },
    {
      id: "u3",
      nombres: "Ana",
      apellidos: "Gómez",
      cedula: "0609876543",
      nacimiento: "2000-08-05",
      email: "ana@mail.com",
      telefono: "+593995551111",
      direccion: "Centro",
      genero: "Mujer",
      foto: "",
      obraSocial: "Privada",
      notas: "",
      tipo: "Cliente",
      activo: true,
      membresia: "m1",
      inscritoPrimera: d(10),
      membresiaInicio: d(5),
      membresiaFin: d(-25),
      saldo: 0,
      ultimoIngreso: d(0),
      creadoAt: d(0),
    },
    {
      id: "u4",
      nombres: "Pedro",
      apellidos: "Cedeño",
      cedula: "0912345678",
      nacimiento: "1988-08-29",
      email: "pedro@mail.com",
      telefono: "+593994443333",
      direccion: "Sur",
      genero: "Hombre",
      foto: "",
      obraSocial: "",
      notas: "Requiere asesorías",
      tipo: "Cliente",
      activo: false,
      membresia: "m1",
      inscritoPrimera: d(800),
      membresiaInicio: d(120),
      membresiaFin: d(30),
      saldo: 50,
      ultimoIngreso: d(61),
      creadoAt: d(120),
    },
    // Usuarios con membresías caducadas
    {
      id: "u5",
      nombres: "Carlos",
      apellidos: "Mendoza",
      cedula: "1203456789",
      nacimiento: "1992-03-15",
      email: "carlos@mail.com",
      telefono: "+593998887776",
      direccion: "Norte",
      genero: "Hombre",
      foto: "",
      obraSocial: "",
      notas: "Cliente frecuente",
      tipo: "Cliente",
      activo: true,
      membresia: "m2",
      inscritoPrimera: d(300),
      membresiaInicio: d(100),
      membresiaFin: d(-15),
      saldo: 25,
      ultimoIngreso: d(20),
      creadoAt: d(100),
    },
    {
      id: "u6",
      nombres: "Sofia",
      apellidos: "Vargas",
      cedula: "1304567890",
      nacimiento: "1997-12-08",
      email: "sofia@mail.com",
      telefono: "+593997776665",
      direccion: "Este",
      genero: "Mujer",
      foto: "",
      obraSocial: "IESS",
      notas: "Prefiere clases de yoga",
      tipo: "Cliente",
      activo: true,
      membresia: "m1",
      inscritoPrimera: d(150),
      membresiaInicio: d(35),
      membresiaFin: d(-8),
      saldo: 0,
      ultimoIngreso: d(10),
      creadoAt: d(35),
    },
    {
      id: "u7",
      nombres: "Roberto",
      apellidos: "Herrera",
      cedula: "1405678901",
      nacimiento: "1985-07-22",
      email: "roberto@mail.com",
      telefono: "+593996665554",
      direccion: "Oeste",
      genero: "Hombre",
      foto: "",
      obraSocial: "",
      notas: "Entrenador personal",
      tipo: "Cliente",
      activo: true,
      membresia: "m3",
      inscritoPrimera: d(500),
      membresiaInicio: d(400),
      membresiaFin: d(-30),
      saldo: 75,
      ultimoIngreso: d(45),
      creadoAt: d(400),
    },
    {
      id: "u8",
      nombres: "Carmen",
      apellidos: "Torres",
      cedula: "1506789012",
      nacimiento: "1993-09-14",
      email: "carmen@mail.com",
      telefono: "+593995554443",
      direccion: "Centro Norte",
      genero: "Mujer",
      foto: "",
      obraSocial: "Privada",
      notas: "Cliente VIP",
      tipo: "Cliente",
      activo: true,
      membresia: "m2",
      inscritoPrimera: d(200),
      membresiaInicio: d(95),
      membresiaFin: d(-5),
      saldo: 15,
      ultimoIngreso: d(2),
      creadoAt: d(95),
    },
    // Usuarios con membresías por caducar (≤5 días)
    {
      id: "u9",
      nombres: "Diego",
      apellidos: "Morales",
      cedula: "1607890123",
      nacimiento: "1991-05-30",
      email: "diego@mail.com",
      telefono: "+593994443332",
      direccion: "Sur Este",
      genero: "Hombre",
      foto: "",
      obraSocial: "",
      notas: "Nuevo cliente",
      tipo: "Cliente",
      activo: true,
      membresia: "m1",
      inscritoPrimera: d(30),
      membresiaInicio: d(25),
      membresiaFin: d(2),
      saldo: 0,
      ultimoIngreso: d(1),
      creadoAt: d(25),
    },
    {
      id: "u10",
      nombres: "Patricia",
      apellidos: "Rojas",
      cedula: "1708901234",
      nacimiento: "1989-11-18",
      email: "patricia@mail.com",
      telefono: "+593993332221",
      direccion: "Norte Oeste",
      genero: "Mujer",
      foto: "",
      obraSocial: "IESS",
      notas: "Cliente regular",
      tipo: "Cliente",
      activo: true,
      membresia: "m2",
      inscritoPrimera: d(180),
      membresiaInicio: d(85),
      membresiaFin: d(3),
      saldo: 30,
      ultimoIngreso: d(5),
      creadoAt: d(85),
    },
    {
      id: "u11",
      nombres: "Fernando",
      apellidos: "Silva",
      cedula: "1809012345",
      nacimiento: "1994-02-25",
      email: "fernando@mail.com",
      telefono: "+593992221110",
      direccion: "Centro Sur",
      genero: "Hombre",
      foto: "",
      obraSocial: "",
      notas: "Interesado en crossfit",
      tipo: "Cliente",
      activo: true,
      membresia: "m1",
      inscritoPrimera: d(28),
      membresiaInicio: d(23),
      membresiaFin: d(1),
      saldo: 0,
      ultimoIngreso: d(0),
      creadoAt: d(23),
    },
    {
      id: "u12",
      nombres: "Valeria",
      apellidos: "Castro",
      cedula: "1900123456",
      nacimiento: "1996-06-12",
      email: "valeria@mail.com",
      telefono: "+593991110009",
      direccion: "Este Norte",
      genero: "Mujer",
      foto: "",
      obraSocial: "Privada",
      notas: "Cliente premium",
      tipo: "Cliente",
      activo: true,
      membresia: "m3",
      inscritoPrimera: d(350),
      membresiaInicio: d(360),
      membresiaFin: d(4),
      saldo: 45,
      ultimoIngreso: d(3),
      creadoAt: d(360),
    },
    {
      id: "u13",
      nombres: "Luis",
      apellidos: "Guzmán",
      cedula: "2001234567",
      nacimiento: "1987-04-03",
      email: "luis@mail.com",
      telefono: "+593990009998",
      direccion: "Oeste Sur",
      genero: "Hombre",
      foto: "",
      obraSocial: "",
      notas: "Cliente deportista",
      tipo: "Cliente",
      activo: true,
      membresia: "m2",
      inscritoPrimera: d(170),
      membresiaInicio: d(80),
      membresiaFin: d(5),
      saldo: 20,
      ultimoIngreso: d(4),
      creadoAt: d(80),
    },
    {
      id: "u14",
      nombres: "Gabriela",
      apellidos: "Flores",
      cedula: "2102345678",
      nacimiento: "1998-10-20",
      email: "gabriela@mail.com",
      telefono: "+593998887776",
      direccion: "Centro Este",
      genero: "Mujer",
      foto: "",
      obraSocial: "IESS",
      notas: "Cliente joven",
      tipo: "Cliente",
      activo: true,
      membresia: "m1",
      inscritoPrimera: d(26),
      membresiaInicio: d(21),
      membresiaFin: d(0),
      saldo: 0,
      ultimoIngreso: d(1),
      creadoAt: d(21),
    },
  ];
}

function seedPlantillasWhatsApp() {
  return [
    {
      id: "p1",
      titulo: "Recordatorio de Pago",
      mensaje: "Hola {nombre}, tu membresía vence el {fecha}. Renueva ahora y mantén tu rutina de ejercicios activa. ¡Te esperamos en el gimnasio!",
      categoria: "recordatorio",
      activa: true,
      fechaCreacion: NOW(),
    },
    {
      id: "p2",
      titulo: "Bienvenida",
      mensaje: "¡Bienvenido/a {nombre} al gimnasio! Tu membresía está activa desde hoy. Disfruta de todas nuestras instalaciones y clases.",
      categoria: "bienvenida",
      activa: true,
      fechaCreacion: NOW(),
    },
  ];
}

function seedDescuentos() {
  return [
    {
      id: "d1",
      nombre: "Descuento Anual",
      monto: 20,
      activo: true,
      fechaCreacion: NOW(),
    },
    {
      id: "d2",
      nombre: "Descuento Estudiantil",
      monto: 15,
      activo: true,
      fechaCreacion: NOW(),
    },
  ];
}

// Función para limpiar datos y recargar
function limpiarDatosYRecargar() {
  localStorage.removeItem("gymdb_v1");
  location.reload();
}
